# Generated by Django 6.0.5 on 2026-05-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_comment_parent_alter_comment_post_alter_content_post_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
