# Generated by Django 6.0.5 on 2026-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0003_alter_commentlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to='content_file/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='file',
            field=models.FileField(upload_to='storia_file/'),
        ),
    ]
