# Generated by Django 6.0.5 on 2026-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0004_alter_content_file_alter_stories_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='music',
            field=models.FileField(upload_to='post_music/'),
        ),
    ]
